'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace AracKayitServis
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AracKayitServis.IAracBilgisiService")>  _
    Public Interface IAracBilgisiService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAracBilgisiService/PlakayaGoreAracBilgisiGetir", ReplyAction:="http://tempuri.org/IAracBilgisiService/PlakayaGoreAracBilgisiGetirResponse")>  _
        Function PlakayaGoreAracBilgisiGetir(ByVal plakaNo As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAracBilgisiServiceChannel
        Inherits AracKayitServis.IAracBilgisiService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AracBilgisiServiceClient
        Inherits System.ServiceModel.ClientBase(Of AracKayitServis.IAracBilgisiService)
        Implements AracKayitServis.IAracBilgisiService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function PlakayaGoreAracBilgisiGetir(ByVal plakaNo As String) As String Implements AracKayitServis.IAracBilgisiService.PlakayaGoreAracBilgisiGetir
            Return MyBase.Channel.PlakayaGoreAracBilgisiGetir(plakaNo)
        End Function
    End Class
End Namespace
