'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8669
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class header

    '''<summary>
    '''Literalaktifjavascript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literalaktifjavascript As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Labelokunmamisdosyasayisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelokunmamisdosyasayisi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelokunmamisdosyasayisi2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelokunmamisdosyasayisi2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labeldosyaonizle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labeldosyaonizle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelokunmamismesajsayisi2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelokunmamismesajsayisi2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelokunmamismesajsayisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelokunmamismesajsayisi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelmsgonizle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelmsgonizle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelokunmamiserrorsayi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelokunmamiserrorsayi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelokunmamiserrorsayi2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelokunmamiserrorsayi2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelerroronizle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelerroronizle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Literalloginresim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literalloginresim As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Literalloginkullaniciad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literalloginkullaniciad As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Labelokunmamismesajsayisi3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelokunmamismesajsayisi3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Literalmenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literalmenu As Global.System.Web.UI.WebControls.Literal
End Class
